### PR TITLE
Making things work under windows

### PR DESCRIPTION
**Pull request by samehkhamis**
CMake defines _WIN32.

### CODE REVIEW

**Comment by leonbottou** [comment]
LUA_WIN is the symbol that is defined when lua is compiled under windows.
There is no point changing it (since this symbol is used by all of the lua code.)
- L.

**Comment by samehkhamis** [comment]
Hi Leon,

LUA_WIN is not defined for me. I am linking with LUAJIT 2.1, not sure if this is the reason, and compiling with VS 2013 x64. Most of the packages in distro use _WIN32, except for paths and sys. Any thoughts?

Thank you,
Sameh

**Comment by samehkhamis** [comment]
Hi Leon,
Lua 5.1 defines LUA_WIN, but I cannot find the define in LuaJIT.
Cheers.

**Comment by leonbottou** [comment]
Correct. LUA_WIN disappeared from luaconf.h in luajit. 

- L.

**Comment by soumith** [comment]
thanks Sameh

**Pull request merged**
