### PR TITLE
paths.iterfiles and paths.iterdirs

### PR DESCRIPTION
**Pull request by nicholas-leonard**
Added two functions to paths for iterating files and directories exclusively.

### CODE REVIEW

**Comment by leonbottou** [comment]
In the spirit of minimal API, why not something like:

```Lua
function paths.files(s, optarg)
   local p = optarg
   if optarg == true then
      p = function(s) return paths.dirp(s) and s ~= '.' and s ~= '..'  end
   elseif type(optarg) == 'string' then
      p = function(s) return paths.filep(s) and s:find(optarg) end
   end
   local d = paths.dir(s)
   local n = 0
   return function()
     while true do
        n = n + 1
        if d == nil or n > #d then
          return nil
        elseif p(d[n]) then
          return d[n]
        end
     end
   end
end
```

When argument `optarg` is `true`, this iterator only returns the names of subdirectories, excluding `"."` and `".."` since they are not subdirectories.  When argument `optarg` is a Lua pattern, this iterator only returns names of file that match the provided pattern. When argument `optarg` is a function that takes a string and returns a boolean, this iterator only returns names for which the function returns a logically true result.

**Comment by nicholas-leonard** [comment]
@leonbottou The API is already pretty minimal in my opinion. However, I do like the idea of allowing for a function or string to be passed to `paths.files`. Using that function I could make `paths.iterdirs` and `paths.iterfiles` call `paths.files` with corresponding functions. I really want a `paths.iterfiles` and `paths.iterdirs` because its such a common use case. Also, with this in mind, `optarg` would just be either a function or a string.

**Comment by leonbottou** [comment]
Well, 
 path.iterdirs(s)  == path.files(s,true)
 path.iterfiles(s) == path.files(s,"")
But you can also do
 path.files(s, "%.lua$")
to iterate over the lua files only (something badly needed in my opinion).
The path.files solution has less explicit names, though...

**Comment by nicholas-leonard** [comment]
@leonbottou what do you think about the newest changes?

**Pull request merged**
